name: Checkmarx
on:
  push:
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  Checkmarx-Analysis:
    runs-on: ubuntu-latest

    steps:
    - run: set
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Checkmarx Scan
      uses: checkmarx-ts/checkmarx-cxflow-github-action@9975af7d6b957abec9ee9646effa3fb3b82c5314
      with:
        project: simply_vulnerable_react-${{ github.ref }}
        team: /CxServer/GitHubAction
        checkmarx_url: ${{ secrets.CHECKMARX_URL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        scanners: sast
        incremental: false
        bug_tracker: Sarif
        preset: Checkmarx Express
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
    # Upload the Report for CodeQL/Security Alerts
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
