name: Checkmarx Scan via Action
on: [push,pull_request]
jobs:
  Checkmarx-Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3
        with:
          project: simply_vulnerable_react
          team: /CxServer/GitHubAction
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          bug_tracker: GitHub
          app: SimplyVulnerableReact
          break_build: true
          scanners: sast
# Upload SARIF report for CodeQL / Security Alerts Processing
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: cx.sarif

